# Generated by Django 5.0.6 on 2024-08-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='peso_neto',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
