# Generated by Django 5.0.6 on 2024-08-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0002_alter_exportacion_peso_neto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='fob_dolar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
