# Generated by Django 5.0.6 on 2024-08-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0003_alter_exportacion_fob_dolar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportacion',
            old_name='año',
            new_name='anio',
        ),
    ]
