# Generated by Django 5.0.6 on 2024-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0004_rename_año_exportacion_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportacion',
            name='anio',
        ),
        migrations.AddField(
            model_name='exportacion',
            name='año',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
