# Generated by Django 5.0.6 on 2024-08-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0005_remove_exportacion_anio_exportacion_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportacion',
            old_name='año',
            new_name='anio',
        ),
    ]
