# Generated by Django 5.0.6 on 2024-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportaciones', '0006_rename_año_exportacion_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportacion',
            old_name='anio',
            new_name='año',
        ),
    ]
