# Generated by Django 5.0.6 on 2024-06-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fob_dolar', models.IntegerField(blank=True, null=True)),
                ('peso_neto', models.IntegerField(blank=True, null=True)),
                ('rubro_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
