# Generated by Django 5.0.6 on 2024-08-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_rubro_id_producto_rubro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fob_dolar',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='peso_neto',
        ),
    ]
