# Generated by Django 5.0.6 on 2024-08-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Pregunta')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Respuesta Correcta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaIncorrecta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_incorrect', models.CharField(max_length=255, verbose_name='Respuesta Incorrecta')),
                ('question_inc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_answers', to='trivia.pregunta')),
            ],
        ),
    ]
