# Generated by Django 5.0.6 on 2024-09-01 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaincorrecta',
            name='question_inc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incorrect_answers', to='trivia.pregunta', verbose_name='Pregunta'),
        ),
    ]
